# Generated by Django 5.0 on 2023-12-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_order_delicery_adress_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delicery_adress',
            new_name='delivery_address',
        ),
    ]
